language: python
sudo: false
python:
  - "2.7"
env:
    - TOX_ENV=pep8
    - TOX_ENV=py27
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
notifications:
    flowdock: 1f4ec6febcf1ac9b35ae6c1f0049471f
