##################################################################################
# Cloudify vSphere built in types and plugins definitions.
##################################################################################

plugins:
    vsphere:
        executor: central_deployment_agent
        package_name: cloudify-vsphere-plugin
        install: false
        package_version: '2.0.dev'

node_types:
    cloudify.vsphere.nodes.Server:
        derived_from: cloudify.nodes.Compute
        properties:
            server: {}
            networking: {}
            connection_config:
                default: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                start:
                    implementation: vsphere.vsphere_server_plugin.server.start
                    inputs: {}
                stop:
                    implementation: vsphere.vsphere_server_plugin.server.stop
                    inputs: {}
                shutdown_guest:
                    implementation: vsphere.vsphere_server_plugin.server.shutdown_guest
                    inputs: {}
                delete:
                    implementation: vsphere.vsphere_server_plugin.server.delete
                    inputs: {}
            cloudify.interfaces.host:
                get_state:
                    implementation: vsphere.vsphere_server_plugin.server.get_state
                    inputs: {}

    cloudify.vsphere.nodes.WindowsServer:
        derived_from: cloudify.vsphere.nodes.Server
        properties:
            windows_password:
                description: >
                    Administrator password to set when deploying Windows instances.
                    If this is not supplied, agent_config.password will be used (if that has been supplied).
                    Supplying neither of these properties will result in an error.
                type: string
                required: false
            windows_timezone:
                description: >
                    Timezone to set Windows instances to.
                    See https://msdn.microsoft.com/en-us/library/ms912391%28v=winembedded.11%29.aspx
                    Defaults to GMT without daylight savings.
                type: integer
                default: 90
            os_family:
                default: windows
            agent_config:
                type: cloudify.datatypes.AgentConfig
                default:
                    port: 5985

    cloudify.vsphere.nodes.Network:
        derived_from: cloudify.nodes.Network
        properties:
            network: {}
            connection_config:
                default: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: vsphere.vsphere_network_plugin.network.create
                    inputs: {}
                delete:
                    implementation: vsphere.vsphere_network_plugin.network.delete
                    inputs: {}

    cloudify.vsphere.nodes.Storage:
        derived_from: cloudify.nodes.Volume
        properties:
            storage: {}
            connection_config:
                default: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: vsphere.vsphere_storage_plugin.storage.create
                    inputs: {}
                delete:
                    implementation: vsphere.vsphere_storage_plugin.storage.delete
                    inputs: {}

relationships:
    cloudify.vsphere.port_connected_to_network:
        derived_from: cloudify.relationships.connected_to

    cloudify.vsphere.port_connected_to_server:
        derived_from: cloudify.relationships.connected_to

    cloudify.vsphere.storage_connected_to_server:
        derived_from: cloudify.relationships.connected_to
