##################################################################################
# Cloudify vSphere built in types and plugins definitions.
##################################################################################

plugins:
    vsphere:
        executor: central_deployment_agent
        package_name: cloudify-vsphere-plugin
        package_version: '2.0.1'
        source: https://github.com/cloudify-cosmo/cloudify-vsphere-plugin/archive/2.0.1.zip

data_types:
    cloudify.datatypes.vsphere.Config:
        properties:
            username:
                description: >
                    vSphere username.
                type: string
                required: false
            host:
                description: >
                    vCenter hostname or IP address.
                type: string
                required: false
            password:
                description: >
                    vCenter password.
                type: string
                required: false
            datacenter_name:
                description: >
                    datacenter name.
                type: string
                required: false
            auto_placement:
                description: >
                    Signifies whether to use vSphere's auto-placement instead of the plugin's.
                    Must be true if you are using clusters.
                type: string
                required: false
                default: false
            resource_pool_name:
                description: >
                    Name of a resource pool.
                    Defaults to Resources, which is a hidden resource pool on vSphere.
                type: string
                required: false
                default: 'Resources'
            port:
                description: >
                    vCenter port for SDK.
                type: integer
                required: false
                default: 443

    cloudify.datatypes.vsphere.ServerProperties:
        properties:
            memory:
                description: >
                    Amount of RAM, in MB.
                type: integer
                required: true
            cpus:
                description: >
                    Number of CPUs.
                type: integer
                required: true
            template:
                description: >
                    Virtual machine template from which server will be spawned.
                    See full documentation at docs.getcloudify.org for requirements.
                type: string
                required: true
            name:
                description: >
                    Server name.
                    Will use node name if this is not set.
                    Must consist of only ASCII letters, numbers, and hyphens.
                    Will automatically convert underscores to hyphens.
                type: string
                required: false

    cloudify.datatypes.vsphere.NetworkingProperties:
        properties:
            domain:
                description: >
                    The fully qualified domain name.
                type: string
                required: false
            dns_servers:
                description: >
                    List of DNS servers.
                required: false
            connect_networks:
                description: |
                    List of network interfaces to connect.
                    These should be in the form of dicts with:
                    name: Network name
                    management: true/false- determines if this is a management network interface (default false)
                    external: true/false- determines if this is a external network interface (default false)
                    switch_distributed: determines if this is connected to a distributed port group (default false)
                    use_dhcp: whether to use DHCP for IP addressing (default true)
                    network: network CIDR to use if use_dhcp is false
                    gateway: default gateway to use if use_dhcp is false. You should only set this on one interface.
                    ip: IP address to use if use_dhcp is false
                required: false

node_types:
    cloudify.vsphere.nodes.Server:
        derived_from: cloudify.nodes.Compute
        properties:
            server:
                type: cloudify.datatypes.vsphere.ServerProperties
            networking:
                type: cloudify.datatypes.vsphere.NetworkingProperties
            connection_config:
                default: {}
                type: cloudify.datatypes.vsphere.Config
        interfaces:
            cloudify.interfaces.lifecycle:
                start:
                    implementation: vsphere.vsphere_server_plugin.server.start
                    inputs: {}
                stop:
                    implementation: vsphere.vsphere_server_plugin.server.stop
                    inputs: {}
                shutdown_guest:
                    implementation: vsphere.vsphere_server_plugin.server.shutdown_guest
                    inputs: {}
                delete:
                    implementation: vsphere.vsphere_server_plugin.server.delete
                    inputs: {}
            cloudify.interfaces.host:
                get_state:
                    implementation: vsphere.vsphere_server_plugin.server.get_state
                    inputs: {}

    cloudify.vsphere.nodes.WindowsServer:
        derived_from: cloudify.vsphere.nodes.Server
        properties:
            windows_password:
                description: >
                    Administrator password to set when deploying Windows instances.
                    If this is not supplied, agent_config.password will be used (if that has been supplied).
                    Supplying neither of these properties will result in an error.
                type: string
                required: false
            windows_timezone:
                description: >
                    Timezone to set Windows instances to.
                    See https://msdn.microsoft.com/en-us/library/ms912391%28v=winembedded.11%29.aspx
                    Defaults to GMT without daylight savings.
                type: integer
                default: 90
            os_family:
                default: windows
            agent_config:
                type: cloudify.datatypes.AgentConfig
                default:
                    port: 5985

    cloudify.vsphere.nodes.Network:
        derived_from: cloudify.nodes.Network
        properties:
            network: {}
            connection_config:
                default: {}
                type: cloudify.datatypes.vsphere.Config
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: vsphere.vsphere_network_plugin.network.create
                    inputs: {}
                delete:
                    implementation: vsphere.vsphere_network_plugin.network.delete
                    inputs: {}

    cloudify.vsphere.nodes.Storage:
        derived_from: cloudify.nodes.Volume
        properties:
            storage: {}
            connection_config:
                default: {}
                type: cloudify.datatypes.vsphere.Config
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: vsphere.vsphere_storage_plugin.storage.create
                    inputs: {}
                delete:
                    implementation: vsphere.vsphere_storage_plugin.storage.delete
                    inputs: {}

relationships:
    cloudify.vsphere.port_connected_to_network:
        derived_from: cloudify.relationships.connected_to

    cloudify.vsphere.port_connected_to_server:
        derived_from: cloudify.relationships.connected_to

    cloudify.vsphere.storage_connected_to_server:
        derived_from: cloudify.relationships.connected_to
